version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.2
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make get
      - run: make test
